name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: anesis-dev/anesis-cli/.github/workflows/registry-lint.yml@main
    with:
      caller: addons
